# fly.toml app configuration file generated for tuneer on 2024-03-18T21:20:17-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tuneer"
primary_region = "sea"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
